name: "TESTING"
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set environment value
        run: |
          echo "add=15" >> "$GITHUB_ENV"
      
      - name: print env value
        run: echo "variable value is - $add"
          
