name: FIRST_TEST_WORKFLOWS
on: workflow_dispatch
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: list
        run: |
            pwd
            ls
            
      - name: calling action 1
        uses: ./test_action
        with:
          a: 7
          b: 5
          
      - name: calling action 2
        uses: shamsoddin-mujawar/gha-demo/test_action@main
        with:
          a: 3
          b: 2


